---
- hosts: all
  gather_facts: yes
  become: no

  vars:
    docker_mycroft_workdir: ~/docker-mycroft
    docker_mycroft_repository: https://github.com/smartgic/docker-mycroft.git
    docker_mycroft_branch: master
    docker_mycroft_namespace: smartgic
    docker_mycroft_tag: latest
    docker_mycroft_version: master
    docker_mycroft_username:
    docker_mycroft_password:

  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_mycroft_username }}"
        password: "{{ docker_mycroft_password }}"

    - name: Retrieve Dockerfiles from Git
      git:
        repo: "{{ docker_mycroft_repository }}"
        dest: "{{ docker_mycroft_workdir }}"
        version: "{{ docker_mycroft_branch }}"

    - name: Build Docker dev images
      shell:
        cmd: |
          docker buildx build \
            -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:{{ docker_mycroft_tag }} \
            -t {{ docker_mycroft_namespace }}/mycroft-{{ item }}:latest \
            --build-arg TAG={{ docker_mycroft_tag }} \
            --build-arg BRANCH={{ docker_mycroft_version }} \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --push {{ docker_mycroft_workdir }}/{{ item }}/
        executable: /bin/bash
      loop:
        - base
        - audio
        - bus
        - cli
        - enclosure
        - skills
        - voice

    - name: Logout from DockerHub
      docker_login:
        state: absent
